### ISSUE TITLE
Warning appears when a player joins the server

### ISSUE THREAD

**Issue by skyQuiz** [Chival-Network/Core#2]
```java
[Craft Scheduler Thread - 70/WARN]: [Core] Plugin Core v0.0.3 generated an exception while executing task 241
java.lang.NoSuchMethodError: 'boolean me.neznamy.tab.api.TabPlayer.isOnline()'
        at au.chival.core.util.Utils$1.run(Utils.java:79) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by infinity-atom** [comment]
This is related to issue #5
