### ISSUE TITLE
Unable to pass event UserDataRecalculateEvent to handler 

### ISSUE THREAD

**Issue by infinity-atom** [Chival-Network/Core#5]
```java
Unable to pass event UserDataRecalculateEvent to handler au.chival.core.listener.LuckpermsEvents$$Lambda$5753/0x00000008020e28c8
java.lang.NoClassDefFoundError: me/neznamy/tab/api/TabAPI
        at au.chival.core.util.Utils.updateTab(Utils.java:65) ~[core-0.0.3.jar:?]
        at au.chival.core.listener.LuckpermsEvents.onUserUpdated(LuckpermsEvents.java:24) ~[core-0.0.3.jar:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:94) ~[?:?]
        at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:42) ~[?:?]
        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[?:?]
        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:82) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:125) ~[?:?]
        at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:140) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.TabAPI
        ... 14 more
```

Using `v2`

**Comment by infinity-atom** [comment]
It's about `getPlayer()` being non-existent from `me.neznamy.tab.api.TabAPI`
